name: Setup
description: Setup Node.js and install dependencies

runs:
  using: composite
  steps:
    - uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # 4.3.0
      with:
        node-version: 18.20.7
    - name: Use npm 9.9.1. Reference these GH issues https://github.com/yarnpkg/yarn/issues/3728#issuecomment-1737249792, https://github.com/npm/cli/pull/6554#issuecomment-1780237375
      shell: bash
      run: npm install -g npm@9.9.1
    - name: Cache Node Modules
      id: node-cache
      uses: actions/cache@d4323d4df104b026a6aa633fdb11d772146be0bf # 4.2.2
      with:
        path: |
          node_modules
          .cache
        key: node-modulesc-${{ hashFiles('yarn.lock') }}
    - name: Install dependencies
      if: steps.node-cache.outputs.cache-hit != 'true'
      shell: bash
      run: yarn install
